# Variables
@baseUrl = http://localhost:3333

# GET Health check (Status)
# @name getStatus
GET {{baseUrl}}/status

###

# GET rooms
# @name getRoom
GET {{baseUrl}}/rooms

###

# POST rooms
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala create teste http-client",
  "description": "Essa é uma sala de teste no http-client"
}

###

@roomId = {{getRoom.response.body.$.[0].id}}
@createRoomId = {{createRoom.response.body.$.roomId}}
###

# GET rooms
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# POST rooms
# @name createRoomQuestion
#POST {{baseUrl}}/rooms/{{createRoomId}}/questions
POST http://localhost:3333/rooms/6f05315b-1442-4bfa-af46-cf39d951f59e/questions 
Content-Type: application/json

{
  "question": "Essa é uma questão de teste criada no http-client"
}


# curl -s -X GET 'http://localhost:3333/rooms/e06fd7f6-2090-4105-f0db-55807961e7b0/questions' | jq

